Models/Proforma.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace appTsane.Models{


[Table("t_proforma")]
    public class Proforma
    {

[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("id")]
        public int ID {get; set;}


      public String UserID {get; set;}

        public Producto Producto {get; set;}

        public int Quantity{get; set;}

        public Decimal Price { get; set; }



    }











}

Controllers/ProformaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using appTsane.Data;
using appTsane.Models;
using Microsoft.AspNetCore.Identity;


namespace plantitas.Controllers
{
    public class ProformaController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ProformaController(ApplicationDbContext context,
        UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        
        // GET: Proforma
        public async Task<IActionResult> Index()
        {
            
            var userID = _userManager.GetUserName(User);
            var items = from o in _context.Carrito select o;
            items = items.
                Include(p => p.Producto).
                Where(s => s.UserID.Equals(userID));
            
           
            
            return View(await items.ToListAsync());
            
           
            
        }

       // GET: Proforma/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proforma = await _context.Carrito
                .FirstOrDefaultAsync(m => m.ID == id);
            if (proforma == null)
            {
                return NotFound();
            }

            return View(proforma);
        }

          // GET: Proforma/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Comprar()
        {
            return View();
        }

        public IActionResult CompraConfirmada()
        {
            return View();
        }

        // POST: Proforma/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,UserID,Quantity,Price")] Proforma proforma)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proforma);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proforma);
        }

       // GET: Proforma/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proforma = await _context.Carrito.FindAsync(id);
            if (proforma == null)
            {
                return NotFound();
            }
            return View(proforma);
        }

        // POST: Proforma/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,UserID,Quantity,Price")] Proforma proforma)
        {
            if (id != proforma.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proforma);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProformaExists(proforma.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proforma);
        }

       // GET: Proforma/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proforma = await _context.Carrito
                .FirstOrDefaultAsync(m => m.ID == id);
            if (proforma == null)
            {
                return NotFound();
            }

            return View(proforma);
        }


        // POST: Proforma/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proforma = await _context.Carrito.FindAsync(id);
            _context.Carrito.Remove(proforma);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



          private bool ProformaExists(int id)
        {
            return _context.Carrito.Any(e => e.ID == id);
        }


    }
    
    
    
    
}

Views/Proforma/CompraConfirmada.cshtml
<h1>Gracias por su compra se a realizado con Exito pronto le llegara su pedido</h1>
<a asp-controller="Proforma" asp-action="Comprar"><button class="btn btn-danger">Regresar</button></a>

Views/Proforma/Comprar.cshtml
@{
    ViewData["Title"] = "Comprar";
}




        </header>
        <div class="creditCardForm">
            <div class="heading">
                <h1>Confirmar Compra</h1>
            </div>
            <div class="payment">
                <form method="POST" asp-controller="Proforma" asp-action="CompraConfirmada">
                    <div class="form-group owner">
                        <label for="owner">Dueño</label>
                        <input type="text" class="form-control" required>
                    </div>
                    <div class="form-group CVV">
                        <label for="cvv">CVV</label>
                        <input type="text" class="form-control" required>
                    </div>
                    <div class="form-group" id="card-number-field">
                        <label for="cardNumber">Numero de Tarjeta</label>
                        <input type="text" class="form-control" required>
                    </div>
                    <div class="form-group" id="expiration-date">
                        <label>Fecha de Expiracion</label>
                        <select>
                            <option value="01">Enero</option>
                            <option value="02">Febrero </option>
                            <option value="03">Marzo</option>
                            <option value="04">Abril</option>
                            <option value="05">Mayo</option>
                            <option value="06">Junio</option>
                            <option value="07">Julio</option>
                            <option value="08">Augosto</option>
                            <option value="09">Septiembre</option>
                            <option value="10">Octubre</option>
                            <option value="11">Noviembre</option>
                            <option value="12">Diciembre</option>
                        </select>
                        <select>
                            <option value="16"> 2016</option>
                            <option value="17"> 2017</option>
                            <option value="18"> 2018</option>
                            <option value="19"> 2019</option>
                            <option value="20"> 2020</option>
                            <option value="21"> 2021</option>
                        </select>
                    </div>
                    <div class="form-group" id="credit_cards">
                        <img src="/img/visa.jpg" id="visa">
                        <img src="/img/mastercard.jpg" id="mastercard">
                        <img src="/img/amex.jpg" id="amex">
                    </div>
                    <div class="form-group" id="pay-now">
                        <a asp-controller="Proforma" asp-action="CompraConfirmada"><button class="btn btn-danger">Confirmar</button></a>
                    </div>
                </form>
                
            </div>
        </div>

    </div>

Views/Proforma/Delete.cshtml
@model appTsane.Models.Proforma

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<div>
    
    <hr />
    <dl class="row">
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <a asp-action="Index"><button class="btn btn-success">Regresar</button></a>
    </form>
</div>

Views/Proforma/Details.cshtml
@model appTsane.Models.Proforma

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>

    <hr />
  
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    
    <a asp-action="Edit" asp-route-id="@Model.ID"><button class="btn btn-primary">Editar</button></a>
    <a asp-action="Index"><button class="btn btn-success"> Regresar</button></a>
</div>

Views/Proforma/Edit.cshtml
@model appTsane.Models.Proforma


@{
    ViewData["Title"] = "Edit";
}

<h1 style="text-align:center;">Editar Lista de Compras</h1>

<hr />


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="UserID" class="control-label">Usuarios</label>
                <input asp-for="UserID" class="form-control" />
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label">Cantidad</label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                 <a asp-action="Index"><button class="btn btn-success"> Regresar</button></a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Proforma/Index.cshtml
@model IEnumerable<appTsane.Models.Proforma>


@{
    ViewData["Title"] = "Index";
}

<h1 style="text-align: center;">Lista de Compras</h1>
<br>


<table class="table table-dark table-striped mt-4">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Producto.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th scope="col">Acciones</th>
            <th></th>
        </tr>
    </thead>

  <tbody>



@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Producto.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID"><button class="btn btn-primary">Editar</button></a> 
                <a asp-action="Details" asp-route-id="@item.ID"><button class="btn btn-info">Detalles</button></a> 
                <a asp-action="Delete" asp-route-id="@item.ID"><button class="btn btn-danger">Eliminar</button></a>
                 <a asp-controller="Proforma" asp-action="Comprar"><button class="btn btn-danger">Comprar</button></a>
            </td>
        </tr>
}
    </tbody>

    </table>